name: UU Create Release Tag
permissions:
  contents: write

on:
  workflow_call:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string
    secrets:
      RELEASE_PAT:
        required: true
  
jobs:
  create-tag:
    name: Create Release Tag (${{ inputs.version }})
    runs-on: ubuntu-latest
    steps:
      - name: Create Release Tag
        uses: SilverPineSoftware/UUKotlinBuild/.github/actions/uu-create-release-tag@main
        with:
          version: ${{ inputs.version }}
          release_pat: ${{ secrets.RELEASE_PAT }}

